server:
  port: 8080

management:
  tracing:
      sampling:
        probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
