server:
  port: 8504

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:9000/staff
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
